JavaSSLServer:
	javac JavaSSLServer.java
	java -Djavax.net.ssl.keyStore=/workspaces/netprog/prog4/op2/keystore/examplestore -Djavax.net.ssl.keyStorePassword=password JavaSSLServer

JavaSSLClient:
	javac JavaSSLClient.java
	java -Djavax.net.ssl.trustStore=/workspaces/netprog/prog4/op2/keystore/examplestore -Djavax.net.ssl.trustStorePassword=password JavaSSLClient
